
import React, { useState, useRef } from 'react';
import { ScanReport, AppConfig, RiskLevel } from '../types';
import { Database, FileJson, Loader2, FileText, Printer, FileCode, ShieldCheck, Download, Zap, ShieldAlert, Cpu, Lock, Terminal, Shield, UserCheck, FileSpreadsheet } from 'lucide-react';

interface ReportViewProps {
  report: ScanReport | null;
  config?: AppConfig;
}

const ReportView: React.FC<ReportViewProps> = ({ report, config }) => {
  const [isExporting, setIsExporting] = useState<string | null>(null);
  const pdfRef = useRef<HTMLDivElement>(null);

  // 辅助函数：确保 IP 地址中的点是标准半角点
  const formatIP = (ip: string) => {
    if (!ip) return '';
    return ip.replace(/。/g, '.').replace(/．/g, '.').trim();
  };

  /**
   * 核心逻辑：解析最终显示的元数据
   */
  const getResolvedMeta = () => {
    if (!report) return { assetName: '未命名资产', securityLevel: '三级', location: '未知', evaluator: '未知' };
    
    const rMeta = report.metadata;
    const dMeta = config?.defaultMetadata || { 
      assetNamePrefix: 'SVR-', 
      securityLevel: '三级', 
      location: '未知机房', 
      evaluator: '默认审计员' 
    };

    return {
      assetName: (rMeta?.assetName && rMeta.assetName.trim() !== '') ? rMeta.assetName : `${dMeta.assetNamePrefix}${report.target}`,
      securityLevel: (rMeta?.securityLevel && rMeta.securityLevel.trim() !== '') ? rMeta.securityLevel : dMeta.securityLevel,
      location: (rMeta?.location && rMeta.location.trim() !== '') ? rMeta.location : dMeta.location,
      evaluator: (rMeta?.evaluator && rMeta.evaluator.trim() !== '') ? rMeta.evaluator : dMeta.evaluator
    };
  };

  const meta = getResolvedMeta();

  // 辅助函数：按 MLPS 域分组缺陷
  const groupDefectsByDomain = () => {
    if (!report) return {};
    const groups: Record<string, typeof report.defects> = {};
    
    report.defects.forEach(d => {
      // 解析条款 G3-安全通信网络-xxx -> 安全通信网络
      const parts = d.mlps_clause.split('-');
      const domain = parts.length >= 2 ? parts[1] : '其他安全问题';
      if (!groups[domain]) groups[domain] = [];
      groups[domain].push(d);
    });
    return groups;
  };

  // 辅助函数：计算风险统计
  const getRiskStats = () => {
    if (!report) return { high: { count: 0, pct: '0%' }, medium: { count: 0, pct: '0%' }, low: { count: 0, pct: '0%' }, total: 0 };
    const total = report.defects.length;
    if (total === 0) return { high: { count: 0, pct: '0%' }, medium: { count: 0, pct: '0%' }, low: { count: 0, pct: '0%' }, total: 0 };

    const high = report.summary.high;
    const medium = report.summary.medium;
    const low = report.summary.low;

    return {
      high: { count: high, pct: ((high / total) * 100).toFixed(1) + '%' },
      medium: { count: medium, pct: ((medium / total) * 100).toFixed(1) + '%' },
      low: { count: low, pct: ((low / total) * 100).toFixed(1) + '%' },
      total
    };
  };

  const downloadPdf = () => {
    if (!report || !pdfRef.current) return;
    setIsExporting('PDF_CLIENT');

    const element = pdfRef.current;
    const sanitizedIp = formatIP(report.target).replace(/\./g, '_');
    
    const opt = {
      margin: 0, // 页面边距由 CSS 控制
      filename: `DJBH_Report_${sanitizedIp}_${new Date().toISOString().split('T')[0]}.pdf`,
      image: { type: 'jpeg', quality: 1 }, // 最高质量
      html2canvas: { 
        scale: 2, // 提高清晰度
        useCORS: true, 
        backgroundColor: '#ffffff',
        letterRendering: true
      },
      jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
      pagebreak: { mode: ['avoid-all', 'css', 'legacy'] } // 优化分页
    };

    // @ts-ignore
    window.html2pdf().set(opt).from(element).save().then(() => {
      setIsExporting(null);
    });
  };

  const downloadMarkdown = () => {
    if (!report) return;
    setIsExporting('MD');

    const targetIp = formatIP(report.target);
    const mdContent = `
# 网络安全技术审计报告 (NetAudit Pro)

## 1. 测评对象基本信息
- **设备名称**: ${meta.assetName}
- **等保等级**: ${meta.securityLevel}
- **物理位置**: ${meta.location}
- **审计负责人**: ${meta.evaluator}
- **目标 IP**: ${targetIp}
- **审计时间**: ${report.timestamp}

## 2. 审计结论与评分
**安全得分**: ${report.score} / 100
**风险概览**: 高危(${report.summary.high}) 中危(${report.summary.medium}) 低危(${report.summary.low})

---

## 3. 合规缺陷详情
${report.defects.map(d => `
### [${d.risk_level}] ${d.check_item}
- **涉及条款**: ${d.mlps_clause}
- **风险描述**: ${d.description}
- **建议措施**: ${d.suggestion}
`).join('\n')}

---
*Generated by NetAudit Pro v3.1 (STABLE)*
    `.trim();

    const blob = new Blob([mdContent], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `NetAudit_${targetIp.replace(/\./g, '_')}.md`;
    a.click();
    setIsExporting(null);
  };

  const exportToJson = () => {
    if (!report) return;
    setIsExporting('JSON');
    const sanitizedIp = formatIP(report.target).replace(/\./g, '_');
    
    setTimeout(() => {
      const dataStr = JSON.stringify(report, null, 2);
      const dataUri = 'data:application/json;charset=utf-8,' + encodeURIComponent(dataStr);
      const linkElement = document.createElement('a');
      linkElement.setAttribute('href', dataUri);
      linkElement.setAttribute('download', `NetAudit_${sanitizedIp}.json`);
      linkElement.click();
      setIsExporting(null);
    }, 500);
  };

  const downloadWordReport = async () => {
    if (!report || !report.id) return;
    setIsExporting('WORD');
    
    try {
      const apiBaseUrl = config?.apiBaseUrl || 'http://localhost:8000';
      const response = await fetch(`${apiBaseUrl}/api/report/word/${report.id}`, {
        method: 'POST',
      });
      
      if (!response.ok) {
        throw new Error('生成 Word 报告失败');
      }
      
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      const sanitizedIp = formatIP(report.target).replace(/\./g, '_');
      a.download = `NetAudit_Report_${sanitizedIp}_${Date.now()}.docx`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
    } catch (error) {
      console.error('下载 Word 报告失败:', error);
      alert('下载 Word 报告失败，请稍后重试');
    } finally {
      setIsExporting(null);
    }
  };

  const downloadPdfReport = async () => {
    if (!report || !report.id) return;
    setIsExporting('PDF_SERVER');
    
    try {
      const apiBaseUrl = config?.apiBaseUrl || 'http://localhost:8000';
      const response = await fetch(`${apiBaseUrl}/api/report/pdf/${report.id}`, {
        method: 'POST',
      });
      
      if (!response.ok) {
        throw new Error('生成 PDF 报告失败');
      }
      
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      const sanitizedIp = formatIP(report.target).replace(/\./g, '_');
      a.download = `NetAudit_Report_${sanitizedIp}_${Date.now()}.pdf`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
    } catch (error) {
      console.error('下载 PDF 报告失败:', error);
      alert('下载 PDF 报告失败，请稍后重试');
    } finally {
      setIsExporting(null);
    }
  };

  if (!report) {
    return (
      <div className="flex flex-col items-center justify-center h-[600px] tactical-card rounded-[4rem] border-dashed border-white/5 relative overflow-hidden bg-black/20">
        <Database size={48} className="text-white/10 mb-6 animate-pulse" />
        <span className="text-xs font-black uppercase tracking-[0.5em] text-white/20 italic">报告归档库空置</span>
      </div>
    );
  }

  const groupedDefects = groupDefectsByDomain();
  const riskStats = getRiskStats();
  
  // 生成报告编号：DJBH-年份-时间戳后几位
  const reportCode = `DJBH-${new Date().getFullYear()}-${report.timestamp.replace(/[-: ]/g, '').substring(0, 14)}`;

  return (
    <div className="space-y-12 animate-in fade-in duration-1000 max-w-5xl mx-auto pb-20">
      <div className="tactical-card rounded-[3.5rem] border border-white/10 overflow-hidden relative group shadow-2xl">
        <div className="absolute inset-0 scanline-container opacity-10 pointer-events-none"></div>
        
        <div className="p-12 md:p-16 flex flex-col items-center text-center relative z-10">
          <div className="w-24 h-24 bg-brand/10 border border-brand/20 rounded-3xl flex items-center justify-center mb-10 shadow-xl">
            <ShieldCheck size={50} className="text-brand" />
          </div>
          
          <h2 className="text-6xl font-black italic uppercase tracking-tighter glow-text mb-2">档案导出终端</h2>
          <p className="text-[10px] font-bold text-white/20 uppercase tracking-[0.6em] mb-12">DEEP ARCHIVE EXPORT TERMINAL</p>

          <div className="w-full max-w-3xl grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">
              <div className="bg-white/5 p-4 rounded-2xl border border-white/5 text-left">
                  <span className="text-[8px] font-black text-white/20 uppercase block mb-1">设备名称</span>
                  <span className="text-xs font-bold text-white truncate block">{meta.assetName}</span>
              </div>
              <div className="bg-white/5 p-4 rounded-2xl border border-white/5 text-left">
                  <span className="text-[8px] font-black text-white/20 uppercase block mb-1">等保等级</span>
                  <span className="text-xs font-bold text-brand block">{meta.securityLevel}</span>
              </div>
              <div className="bg-white/5 p-4 rounded-2xl border border-white/5 text-left">
                  <span className="text-[8px] font-black text-white/20 uppercase block mb-1">物理位置</span>
                  <span className="text-xs font-bold text-white/60 truncate block">{meta.location}</span>
              </div>
              <div className="bg-white/5 p-4 rounded-2xl border border-white/5 text-left">
                  <span className="text-[8px] font-black text-white/20 uppercase block mb-1">测评员</span>
                  <span className="text-xs font-bold text-info block">{meta.evaluator}</span>
              </div>
          </div>

          <div className="flex flex-wrap justify-center gap-6 w-full">
             <button onClick={downloadWordReport} disabled={!!isExporting} className="group relative px-10 py-6 bg-gradient-to-r from-blue-600 to-blue-500 text-white rounded-2xl font-black uppercase italic text-sm flex items-center gap-4 hover:from-blue-700 hover:to-blue-600 transition-all disabled:opacity-50 min-w-[260px] shadow-lg">
               {isExporting === 'WORD' ? <Loader2 size={20} className="animate-spin" /> : <FileSpreadsheet size={20} />}
               <div className="text-left">
                 <span className="block leading-none">等保 Word 报告</span>
                 <span className="text-[8px] opacity-80 font-bold block mt-1 tracking-widest uppercase">GB/T 22239-2019</span>
               </div>
             </button>
             <button onClick={downloadPdf} disabled={!!isExporting} className="group relative px-10 py-6 bg-gradient-to-r from-red-600 to-red-500 text-white rounded-2xl font-black uppercase italic text-sm flex items-center gap-4 hover:from-red-700 hover:to-red-600 transition-all disabled:opacity-50 min-w-[260px] shadow-lg">
               {isExporting === 'PDF_CLIENT' ? <Loader2 size={20} className="animate-spin" /> : <Printer size={20} />}
               <div className="text-left">
                 <span className="block leading-none">等保 PDF 报告</span>
                 <span className="text-[8px] opacity-80 font-bold block mt-1 tracking-widest uppercase">Standard Compliance</span>
               </div>
             </button>
             <button onClick={downloadMarkdown} disabled={!!isExporting} className="px-10 py-6 bg-white/5 border border-white/10 text-white rounded-2xl font-black uppercase italic text-sm flex items-center gap-4 hover:bg-white/10 transition-all min-w-[260px]">
               {isExporting === 'MD' ? <Loader2 size={20} className="animate-spin" /> : <FileCode size={20} className="text-info" />}
               <div className="text-left">
                 <span className="block leading-none">导出 Markdown</span>
                 <span className="text-[8px] opacity-40 font-bold block mt-1 tracking-widest uppercase">Security Document</span>
               </div>
             </button>
             <button onClick={exportToJson} disabled={!!isExporting} className="px-10 py-6 bg-white/5 border border-white/10 text-white rounded-2xl font-black uppercase italic text-sm flex items-center gap-4 hover:bg-white/10 transition-all min-w-[260px]">
               {isExporting === 'JSON' ? <Loader2 size={20} className="animate-spin" /> : <FileJson size={20} className="text-brand" />}
               <div className="text-left">
                 <span className="block leading-none">JSON 数据流</span>
                 <span className="text-[8px] opacity-40 font-bold block mt-1 tracking-widest uppercase">System Raw Data</span>
               </div>
             </button>
          </div>
        </div>
      </div>

      {/* =====================================================================================
          PDF 模板：严格复刻 GB/T 22239 标准报告样式
          ===================================================================================== */}
      <div className="fixed -left-[5000px] top-0 pointer-events-none">
        <div 
           ref={pdfRef} 
           className="w-[210mm] min-h-[297mm] bg-white text-black font-serif leading-normal relative text-sm"
           style={{ fontFamily: '"SimSun", "Songti SC", serif' }}
        >
          {/* --- 封面页 --- */}
          <div className="h-[297mm] flex flex-col justify-center items-center p-16 relative page-break-after-always">
             <h1 className="text-[34px] font-bold text-center mb-32 tracking-wider" style={{ fontFamily: '"SimHei", "Heiti SC", sans-serif' }}>
               信息系统安全等级保护测评报告
             </h1>

             <table className="w-full border-collapse border border-gray-400 text-base">
                <tbody>
                   <tr>
                      <td className="border border-gray-400 p-4 bg-gray-50 font-bold w-1/3">报告编号</td>
                      <td className="border border-gray-400 p-4">{reportCode}</td>
                   </tr>
                   <tr>
                      <td className="border border-gray-400 p-4 bg-gray-50 font-bold">系统/设备名称</td>
                      <td className="border border-gray-400 p-4">{meta.assetName}</td>
                   </tr>
                   <tr>
                      <td className="border border-gray-400 p-4 bg-gray-50 font-bold">目标地址</td>
                      <td className="border border-gray-400 p-4">{formatIP(report.target)}</td>
                   </tr>
                   <tr>
                      <td className="border border-gray-400 p-4 bg-gray-50 font-bold">系统定级</td>
                      <td className="border border-gray-400 p-4">{meta.securityLevel}</td>
                   </tr>
                   <tr>
                      <td className="border border-gray-400 p-4 bg-gray-50 font-bold">物理位置</td>
                      <td className="border border-gray-400 p-4">{meta.location}</td>
                   </tr>
                   <tr>
                      <td className="border border-gray-400 p-4 bg-gray-50 font-bold">测评负责人</td>
                      <td className="border border-gray-400 p-4">{meta.evaluator}</td>
                   </tr>
                   <tr>
                      <td className="border border-gray-400 p-4 bg-gray-50 font-bold">测评时间</td>
                      <td className="border border-gray-400 p-4">{report.timestamp}</td>
                   </tr>
                </tbody>
             </table>
          </div>

          {/* --- 第一章：测评结果概述 --- */}
          <div className="p-12 min-h-[297mm] relative page-break-after-always">
             <h2 className="text-2xl font-bold mb-8" style={{ fontFamily: '"SimHei", "Heiti SC", sans-serif' }}>第一章 测评结果概述</h2>
             
             <div className="mb-8 text-base">
                <p className="mb-4">综合安全评分：<span className="font-bold text-lg">{report.score} / 100</span></p>
                <p className="leading-relaxed">
                   系统安全防护能力{report.score >= 80 ? '基本符合' : '不符合'}等级保护{meta.securityLevel}要求，
                   {report.score < 60 ? '存在严重安全风险，必须立即进行整改加固。' : '仍存在部分安全隐患，建议按期整改。'}
                </p>
             </div>

             <div className="mb-4 font-bold">本次测评共发现 {report.defects.length} 个安全问题：</div>
             
             <table className="w-full border-collapse border border-gray-400 text-center mb-10">
                <thead>
                   <tr className="bg-[#4a90e2] text-white">
                      <th className="border border-gray-400 p-3 font-bold w-1/4">风险等级</th>
                      <th className="border border-gray-400 p-3 font-bold w-1/4">数量</th>
                      <th className="border border-gray-400 p-3 font-bold w-1/4">占比</th>
                      <th className="border border-gray-400 p-3 font-bold w-1/4">整改期限</th>
                   </tr>
                </thead>
                <tbody>
                   <tr>
                      <td className="border border-gray-400 p-3">高危</td>
                      <td className="border border-gray-400 p-3 text-red-600 font-bold">{riskStats.high.count}</td>
                      <td className="border border-gray-400 p-3">{riskStats.high.pct}</td>
                      <td className="border border-gray-400 p-3">7天内</td>
                   </tr>
                   <tr>
                      <td className="border border-gray-400 p-3">中危</td>
                      <td className="border border-gray-400 p-3 text-orange-600 font-bold">{riskStats.medium.count}</td>
                      <td className="border border-gray-400 p-3">{riskStats.medium.pct}</td>
                      <td className="border border-gray-400 p-3">30天内</td>
                   </tr>
                   <tr>
                      <td className="border border-gray-400 p-3">低危</td>
                      <td className="border border-gray-400 p-3 text-blue-600 font-bold">{riskStats.low.count}</td>
                      <td className="border border-gray-400 p-3">{riskStats.low.pct}</td>
                      <td className="border border-gray-400 p-3">60天内</td>
                   </tr>
                </tbody>
             </table>
          </div>

          {/* --- 第二章：安全技术测评详情 --- */}
          <div className="p-12 relative">
             <h2 className="text-2xl font-bold mb-8" style={{ fontFamily: '"SimHei", "Heiti SC", sans-serif' }}>第二章 安全技术测评详情</h2>
             
             {Object.entries(groupedDefects).map(([domain, defects], domainIndex) => (
                <div key={domain} className="mb-8">
                   <h3 className="text-xl font-bold mb-6 mt-4 border-b-2 border-gray-200 pb-2" style={{ fontFamily: '"SimHei", "Heiti SC", sans-serif' }}>
                      {domainIndex + 1}. {domain}
                   </h3>
                   
                   {defects.map((d, i) => (
                      <div key={i} className="mb-8 break-inside-avoid">
                         <table className="w-full border-collapse border border-gray-400 text-sm">
                            <tbody>
                               {/* 标题行：问题描述 */}
                               <tr>
                                  <td colSpan={2} className="border border-gray-400 p-2 bg-gray-100 font-bold">
                                     问题 #{i + 1}：{d.check_item}
                                  </td>
                               </tr>
                               {/* 风险等级 */}
                               <tr>
                                  <td className="border border-gray-400 p-2 w-32 font-bold text-center bg-gray-50 align-middle">风险等级</td>
                                  <td className={`border border-gray-400 p-2 font-bold align-middle ${d.risk_level === '高危' ? 'text-red-600' : d.risk_level === '中危' ? 'text-orange-600' : 'text-blue-600'}`}>
                                     {d.risk_level}
                                  </td>
                               </tr>
                               {/* 检测协议 */}
                               <tr>
                                  <td className="border border-gray-400 p-2 font-bold text-center bg-gray-50 align-middle">检测协议</td>
                                  <td className="border border-gray-400 p-2 align-middle">{d.protocol}</td>
                               </tr>
                               {/* 涉及条款 */}
                               <tr>
                                  <td className="border border-gray-400 p-2 font-bold text-center bg-gray-50 align-middle">涉及条款</td>
                                  <td className="border border-gray-400 p-2 align-middle">{d.mlps_clause}</td>
                               </tr>
                               {/* 问题描述 */}
                               <tr>
                                  <td className="border border-gray-400 p-2 font-bold text-center bg-gray-50 align-middle">问题描述</td>
                                  <td className="border border-gray-400 p-2 align-middle">{d.description}</td>
                               </tr>
                               {/* 整改建议 */}
                               <tr>
                                  <td className="border border-gray-400 p-2 font-bold text-center bg-gray-50 align-middle">整改建议</td>
                                  <td className="border border-gray-400 p-2 align-middle">{d.suggestion}</td>
                               </tr>
                            </tbody>
                         </table>
                      </div>
                   ))}
                </div>
             ))}

             {report.defects.length === 0 && (
                <div className="p-10 text-center border border-dashed border-gray-300 rounded">
                   本系统符合安全技术要求，未发现明显安全隐患。
                </div>
             )}
          </div>

          {/* --- 第三章：结论 --- */}
           <div className="p-12 relative page-break-before-always break-inside-avoid">
             <h2 className="text-2xl font-bold mb-8" style={{ fontFamily: '"SimHei", "Heiti SC", sans-serif' }}>第三章 测评结论与整改要求</h2>
             <div className="space-y-4 text-base leading-relaxed">
                <p>经 NetAudit Pro v3.2 自动化测评，该信息系统的综合安全评分为 <span className="font-bold">{report.score} 分</span>。</p>
                <p className="font-bold mt-6">整改要求：</p>
                <ol className="list-decimal pl-6 space-y-2">
                   <li>高危问题必须在 <span className="font-bold underline">7天内</span> 完成整改（失陷系统需24小时内处理）</li>
                   <li>中危问题必须在 <span className="font-bold underline">30天内</span> 完成整改</li>
                   <li>低危问题必须在 <span className="font-bold underline">60天内</span> 完成整改</li>
                   <li>整改完成后使用 NetAudit Pro 进行复测验证</li>
                </ol>
             </div>
             
             <div className="mt-20 text-center text-gray-500">
                --- 报告结束 ---
             </div>
          </div>

        </div>
      </div>
    </div>
  );
};

export default ReportView;
